"use strict";
exports.__esModule = true;
var src_BinaryTree_1 = require("../src/src_BinaryTree");
var tree = new src_BinaryTree_1.BinaryTree();
tree.insert(6);
tree.insert(5);
tree.insert(7);
tree.insert(3);
tree.insert(4);
console.log("The numbers of nodes ".concat(tree.totalNode));
tree.inorder(tree.root);
